version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout

      - run:
          name: install python dependencies
          command: |
            virtualenv env --no-site-packages
            source env/bin/activate
            pip install -r requirements.txt

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = fernandosure" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            python setup.py sdist

      - run:
          name: upload to pypi
          command: |
            source env/bin/activate
            twine upload dist/*
